myPhone.make = input("What make is your phone: ")
# myPhone.description = input("What features dose your phone have: ")
# myPhone.model = input("What model is it: ")
# myPhone.price= input("What is the cost of your phone: ")
# print(myPhone.make)
# print(myPhone.description)
# print(myPhone.model)
# print(myPhone.price)