-- Like is the equilivent of doing a search through a table for values
-- select * from employee where fname like "j%";
-- select * from employee where fname like "__h_%";
-- select sex, max(salary) from employee where salary is not null group by sex limit 3 offset 4;
-- select * from employee where salaary is not null order by salary desc;
-- select gender, max(salary) from employee group by gender;
-- where clause applies condition to the selected columns, having allows adding a second layer of condition to the retrived data