-- ALTER TABLE Trainer RENAME COLUMN trainerSalary TO annualSalary;
-- ALTER TABLE trainer TO Instructor;
-- ALTER TABLE trainer DROP PRIMARY KEY;
-- ALTER TABLE subject ADD FOREIGN KEY (columnName) REFERENCES Instructor(primaryKey);
-- SELECT * FROM tableName;
--  DELETE removes rows from a table based on a conditions
--  TRUNCATE removes all rows from a table
--  DROP used to remove tables, databases, schemas etc...
-- ALTER TABLE Trainer ADD CONSTRAINT constraint_name PRIMARY KEY (trainerID);
-- ALTER TABLE Trainer ADD COLUMN age INT AFTER lastName;
-- MOdify the structure of the table